name: Development build

on:
  pull_request_review:
    types: [submitted]

jobs:
  dev-build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    name: Development build after approving review
    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, mysqli, intl, curl #optional, setup extensions
        coverage: xdebug #optional, setup coverage driver

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: composer install

    - name: Build for development
      run: PREFIX=/tmp/release make test-zip

    - name: Get version name
      run: echo "DEV_BUILD_VERSION=$(git describe --tags ${{ github.sha }})" >> $GITHUB_ENV

    - name: Rename .zip
      run: mv /tmp/release/onoffice.zip /tmp/release/onoffice-${{ env.DEV_BUILD_VERSION}}.zip

    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: please-unpack-onoffice-${{ env.DEV_BUILD_VERSION }}
        path: /tmp/release/onoffice-${{ env.DEV_BUILD_VERSION }}.zip  # Uploading a .zip leads to a .zip inside a .zip, but uploading the folder takes significantly longer.

    - name: Post comment
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          Install the approved version:
          1. Download `please-unpack-onoffice-${{ env.DEV_BUILD_VERSION }}.zip` from https://github.com/jmaas-onoffice/oo-wp-plugin/actions/runs/${{ github.run_id }}.
          2. Unpack the downloaded file to get another .zip file.
          3. Upload that inner .zip file to WordPress.
        repo-token: ${{ secrets.GITHUB_TOKEN }}