name: Development build

on:
  pull_request_review:
    types: [submitted]

jobs:
  dev-build:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    name: Development build after approving review
    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, mysqli, intl, curl #optional, setup extensions
        coverage: xdebug #optional, setup coverage driver

    - name: Check PHP Version
      run: php -v

    - name: Composer install
      run: composer install

    - name: Build for development
      run: PREFIX=/tmp/release make test-zip

    - name: Get version name
      run: echo "DEV_BUILD_VERSION=$(git describe --tags)" >> $GITHUB_ENV

    - name: Set development version in plugin
      run: sed -i -r "s/Version:\ [^$$]+/Version:\ ${{ env.DEV_BUILD_VERSION }}/" /home/jojo/code/oo-wp-plugin-fork/plugin.php

    - name: Zip development build
      run: zip -r /tmp/release/onoffice-${{ env.DEV_BUILD_VERSION }}.zip /tmp/release/onoffice/

    - name: Upload zip
      uses: actions/upload-artifact@v3
      with:
        name: please-unpack-onoffice-${{ env.DEV_BUILD_VERSION }}
        path: /tmp/release/onoffice.zip  # Uploading a .zip leads to a .zip inside a .zip, but uploading the folder takes significantly longer.

    - name: Post comment
      uses: mshick/add-pr-comment@v1
      with:
        message: |
          Download please-unpack-onoffice-${{ env.DEV_BUILD_VERSION }}.zip from https://github.com/jmaas-onoffice/oo-wp-plugin/actions/runs/${{ github.run_id }}
          Then unpack that file to get another .zip file that you can upload to WordPress.
        repo-token: ${{ secrets.GITHUB_TOKEN }}