name: Email notification for review request

on:
  pull_request_target:
    types: [review_requested]

jobs:
  # We cannot use secrets in `if` conditions for job, so we need to do this workaround.
  check-reviewer:
    runs-on: ubuntu-latest
    outputs:
      wants-email: ${{ steps.want-email.outputs.wants-email}}
    steps:
      - id: wants-email
        run: echo "::set-output name=wants-email::${{ contains(fromJSON(secrets.EMAIL_RECEIVER_GITHUB_USERNAMES), github.event.requested_reviewer.login) }}"

  notify-review-request:
    runs-on: ubuntu-latest
    needs: check-reviewer
    if: needs.check-reviewer.wants-email == 'true'
    name: Send email
    steps:
      - name: Get project ID
        run: echo "PROJECT_ID=$(echo "${{ github.event.pull_request.title }}" | sed -r 's/.*P#([0-9]{5}).*/\1/g')" >> $GITHUB_ENV  

      - name: Send mail test
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_SERVER_ADDRESS }}
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "[WP-Plugin] Review requested for ${{ github.event.pull_request.title }}"
          to: ${{ secrets.EMAIL_RECEIVER_ADDRESS }}
          from: WP-Plugin GitHub Action
          convert_markdown: true
          html_body: |
            A review was requested for a PR on the [WordPress plugin repo](https://github.com/${{ github.repository }}).

            A ticket was created which you can track on. Please make it visible:

            1. Open the project for [${{ github.event.pull_request.title }}](${{ github.event.pull_request.url }}). ([Quick link](${{ secrets.REDIRECT_URL }}${{ env.PROJECT_ID }}))
            2. Ensure that the link to the PR is present in the project requirements such that the link is easily accessible when working on tickets.
            3. Set the project's phase to "In Bearbeitung".
            4. The ticket should appear in your tasks.