name: Release

# Controls when the action will run.
on:
  push:
    # Pattern matched against refs/tags
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-version:
    name: Check version in config files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Check versions
        run: deno run --allow-read scripts/check-version-in-config-files.ts ${{ github.ref_name }}
  deploy:
    name: Deploy WordPress SVN
    runs-on: ubuntu-latest
    needs: check-version
    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.0
        extensions: mbstring, mysqli, intl, curl #optional, setup extensions

    - name: Check PHP Version
      run: php -v
    - name: composer install
      run: composer install