name: Release

# Controls when the action will run.
on:
  push:
    # Pattern matched against refs/tags
    tags:
    - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploy to WordPress SVN
    runs-on: ubuntu-latest
    steps:
    - name: Checkout from GIT
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Get plugin version (without leading 'v')
      run: echo "PLUGIN_VERSION=$(${{ github.ref_name }} | sed -n "s/v\(\)/\1/p") >> $GITHUB_ENV  

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - name: Check versions
      run: deno run --allow-read scripts/check-version-in-config-files.ts ${{ env.PLUGIN_VERSION }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.0
        extensions: mbstring, mysqli, intl, curl

    - name: Install dependencies
      run: composer install
